### ISSUE TITLE
Test model on a single GPU and windows

### ISSUE THREAD

**Issue by FBehrad** [lzqsd/InverseRenderingOfIndoorScene#13]
Hello, 
I have tried to test the model on a single gpu and windows. Unfortunately, I faced too many errors. 
My current problem is the following:
 The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

I solved the problem according to this [link](https://minerl.io/docs/notes/windows.html#:~:text=The%20%22freeze_support()%22%20line%20can,code%20from%20executing%20multiple%20times.).
But, now when I run the code it quickly stops without producing outputs. 

Has anyone ran this repo on a single GPU?

**Comment by FBehrad** [comment]
I used testReal.py and modified the code slightly. Now, its working.

**Comment by huynhtruc0309** [comment]
How you run it with single GPU? Can you provide testReal.py you modified?
