### ISSUE TITLE
Apply Download Link

### ISSUE THREAD

**Issue by ChenLu-china** [lzqsd/InverseRenderingOfIndoorScene#8]
Hi, may I get the access of download link here? I have sent email to OpenRoomsDataset@gmail.com host, but do not get the response. My email is chen-lu.chen@connect.polyu.hk. Waitting for your reply, thanks.

**Comment by lzqsd** [comment]
Hi Chenlu,

That's weird. I checked the inbox but could not find your email in it. I have added you to the contact list and will send you the download links now.
